# Generated by Django 3.1.1 on 2020-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('likeno', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postno', models.AutoField(primary_key=True, serialize=False)),
                ('postdate', models.DateTimeField()),
                ('view', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('video', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('mileage', models.PositiveIntegerField()),
                ('isfinished', models.IntegerField(blank=True, db_column='isFinished', null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyno', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('replydate', models.DateTimeField(blank=True, null=True)),
                ('replyopt', models.IntegerField(db_column='replyOpt')),
            ],
            options={
                'db_table': 'reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userno', models.AutoField(primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=128, unique=True)),
                ('userpw', models.CharField(blank=True, max_length=128, null=True)),
                ('usernickname', models.CharField(max_length=128)),
                ('userimage', models.CharField(blank=True, max_length=256, null=True)),
                ('usercreatedate', models.DateTimeField(blank=True, null=True)),
                ('usersolranknum', models.IntegerField(blank=True, db_column='userSolRankNum', null=True)),
                ('usergameranknum', models.IntegerField(blank=True, db_column='userGameRankNum', null=True)),
                ('usersoltierstr', models.CharField(blank=True, db_column='userSolTierStr', max_length=128, null=True)),
                ('usersolrankstr', models.CharField(blank=True, db_column='userSolRankStr', max_length=128, null=True)),
                ('usergametierstr', models.CharField(blank=True, db_column='userGameTierStr', max_length=128, null=True)),
                ('usergamerankstr', models.CharField(blank=True, db_column='userGameRankStr', max_length=128, null=True)),
                ('summonername', models.CharField(blank=True, db_column='summonerName', max_length=255, null=True)),
                ('usermileage', models.IntegerField(blank=True, db_column='userMileage', null=True)),
                ('providername', models.CharField(blank=True, db_column='providerName', max_length=128, null=True)),
                ('accesstoken', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteno', models.AutoField(primary_key=True, serialize=False)),
                ('usergameranknum', models.IntegerField()),
                ('usersolranknum', models.IntegerField()),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
    ]
