# Generated by Django 3.1.1 on 2020-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamkey', models.IntegerField()),
                ('chamname', models.CharField(max_length=100)),
                ('chamtags', models.CharField(max_length=200)),
                ('dictionary', models.CharField(max_length=200)),
                ('lane', models.CharField(max_length=200)),
                ('mbti', models.CharField(max_length=50)),
                ('winning_rate', models.FloatField()),
                ('goodmbti', models.CharField(max_length=50)),
                ('badmbti', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'champion',
            },
        ),
    ]
